export const AGREGAR_DESPACHO = 'AGREGAR_DESPACHO';
export const AGREGAR_DESPACHO_EXITO = 'AGREGAR_DESPACHO_EXITO';
export const AGREGAR_DESPACHO_ERROR = 'AGREGAR_DESPACHO_ERROR';


export const COMENZAR_DESCARGA_DESPACHOS = 'COMENZAR_DESCARGA_DESPACHOS';
export const DESCARGA_DESPACHOS_EXITO = 'DESCARGA_DESPACHOS_EXITO';
export const DESCARGA_DESPACHOS_ERROR = 'DESCARGA_DESPACHOS_ERROR';

export const OBTENER_DESPACHO_ELIMINAR = 'OBTENER_DESPACHO_ELIMINAR';
export const DESPACHO_ELIMINADO_EXITO = 'DESPACHO_ELIMINADO_EXITO';
export const DESPACHO_ELIMINADO_ERROR = 'DESPACHO_ELIMINADO_ERROR';


export const OBTENER_DESPACHO_EDITAR = 'OBTENER_DESPACHO_EDITAR';
export const COMENZAR_EDICION_DESPACHO = 'COMENZAR_EDICION_DESPACHO';
export const DESPACHO_EDITADO_EXITO = 'DESPACHO_EDITADO_EXITO';
export const DESPACHO_EDITADO_ERROR = 'DESPACHO_EDITADO_ERROR';

export const MOSTRAR_ALERTA ='MOSTRAR_ALERTA';
export const OCULTAR_ALERTA ='OCULTAR_ALERTA';